cameras:
  - machine_id: SHIMA_001
    rtsp_url: rtsp://192.168.21.213:8554
    led_regions:
      - name: status_main
        x: 120
        y: 80
        width: 40
        height: 40

  - machine_id: CAMERA_002
    rtsp_url: rtsp://192.168.21.214:8554
    led_regions:
      - name: status_main
        x: 100
        y: 70
        width: 50
        height: 50

  - machine_id: CAMERA_003
    rtsp_url: rtsp://192.168.21.215:8554
    led_regions:
      - name: status_led
        x: 130
        y: 90
        width: 35
        height: 35

  - machine_id: CAMERA_004
    rtsp_url: rtsp://192.168.21.216:8554
    led_regions:
      - name: power_status
        x: 110
        y: 60
        width: 45
        height: 45
